name: message-depoly

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
        path: ./

    - name: Mkdir public
      run: mkdir public

    - name: Install miller
      run: sudo apt-get install miller

    - name: Generate json
      run: mlr --icsv --ojson cat message.csv > message.json

    - name: Copy json
      run:  cp message.json public/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        REPOSITORY_NAME: xeonds/xdu-planet
        BRANCH: main
        FOLDER: public
